import type { NextPage } from "next";
import Head from "next/head";

import { RiSunFill, RiMoonFill } from "react-icons/ri";
import { motion } from "framer-motion";
import { useEffect, useState } from "react";

import { useScrolling, useMouseWheel } from "react-use";

import Split from "../tools/Split";

const Home: NextPage = () => {
  const [dark, setDark] = useState(true);

  useEffect(() => {
    if (dark) {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
  }, [dark]);

  const mouseY = useMouseWheel();

  return (
    <main
      className="
      overflow-hidden
      max-h-screen  
      relative
      flex flex-col items-center justify-center
      bg-zinc-300 text-zinc-700
      dark:bg-zinc-900
      dark:text-zinc-400
      min-h-screen min-w-full"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="absolute top-3 right-3">
        <motion.div
          onClick={() => setDark(!dark)}
          animate={{ rotateY: dark ? 180 : 0 }}
          transition={{ duration: 1, type: "spring", damping: 9 }}
          className="page
          relative
          cursor-pointer
          grid place-items-center
          h-11 rounded-xl
          bg-zinc-700
          "
        >
          <div
            className="front absolute
     filter drop-shadow-[0_0px_5px_black]"
          >
            <RiSunFill color="rgba(255,255,255,.6)" size={"1.7rem"} />
          </div>

          <div
            className="back absolute
            filter drop-shadow-[0_0_5px_black] 
             "
          >
            <RiMoonFill color="rgba(255,255,255,.5)" size={"1.7rem"} />
          </div>
        </motion.div>
      </section>

      <h1
        className="
        tracking-tighter
        lowercase
        font-accuratist "
      >
        <Split text="anish kanna" />
      </h1>

      <h3>{mouseY}</h3>
    </main>
  );
};

export default Home;
