import type { NextPage } from 'next'
import Head from 'next/head'

import {RiSunFill , RiMoonFill} from 'react-icons/ri'
import {motion} from 'framer-motion'
import { useEffect, useState } from 'react'




const Home: NextPage = () => {

  const [dark,setDark] = useState(false)
   
  useEffect(()=>{
  
    if(dark){
      document.documentElement.classList.add('dark')
    } else{
      document.documentElement.classList.remove('dark')
    }
      
  },[dark])

  return (
    <main 
      className='
      relative
      flex items-center justify-center
      bg-white text-zinc-700
      dark:bg-zinc-900
      dark:text-zinc-300
      min-h-screen min-w-full'
      >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <section
        className='absolute top-5 right-5'>

        <motion.div
          onClick={()=>setDark(!dark)}
          animate={{rotateY: dark? 180 : 0}}
          transition={{duration:1,type:'spring',damping:9}}
          className='page
          relative
          grid place-items-center
          h-14 rounded-xl
          bg-zinc-700
            '>

          <div className='front absolute'>
              <RiSunFill color='#d4d4d8' size={30} />
          </div>

          <div className='back absolute'>
              <RiMoonFill color='#d4d4d8' size={30} />
          </div>




        </motion.div>

      </section>


      <h1 
        className=' 
        font-manrope -tracking-wider'>
        anish kanna
      </h1>

    </main>
  )
}

export default Home
